# Generated by Django 5.0.1 on 2024-02-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
